server:
  host: "localhost"
  port: 8080
database:
  postgres:
    host: "localhost"
    port: 5432
    user: "taxi"
    password: 
    dbname: "portal"
    ssl: "disable"
  mysql:
    host: "localhost"
    port: 3306
    user: "userback"
    password: 
    dbname: "dbback"

